CREATE USER 'admin'@'%' IDENTIFIED VIA mysql_native_password USING 'meudoc';GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `meudoc`.* TO 'admin'@'%';

CREATE DATABASE meudoc;

USE meudoc;

CREATE TABLE DOCUMENTO(
     TIPO VARCHAR (25), 
     ID_ARQUIVO NUMERIC, 
     OBSERVACAO VARCHAR (70), 
     DT_UPLOAD DATE 
)

CREATE TABLE LOGIN (
	ID_ASSINATURA INT ,
    ID_FOTO INT ,
    ID_DIGITAL INT ,
    SENHA VARCHAR(25) ,
    USUARIO VARCHAR(50) 
);

CREATE TABLE PESSOA (
	TIPO BOOLEAN ,-- (0)Pessoa Física (1) Pessoa Jurídica
    NOME_COMPLETO VARCHAR(70) ,
    NASCIMENTO DATE ,
    TELEFONE INT ,
    EMAIL VARCHAR(70) ,
    CPF VARCHAR(11) ,
    CNPJ VARCHAR(15) ,
    RG VARCHAR(7) ,
    ORGAO_EXPEDIDOR VARCHAR(20) ,
    TITULO_ELEITOR VARCHAR(12) ,
    NOME_MAE VARCHAR(70) ,
    NOME_PAI VARCHAR(70)  ,
    END_OBSERVACAO VARCHAR(150) ,
    END_CEP VARCHAR(8) ,
    END_RUA VARCHAR(50) ,
    END_NUMERO VARCHAR(10) ,
    END_BAIRRO VARCHAR(30) ,
    END_COMPLEMENTO VARCHAR(50) ,
    END_PAIS VARCHAR(30) ,
    END_UF VARCHAR(2) ,
    END_CIDADE VARCHAR(25) 
);
CREATE TABLE AUTENTICACAO (
	USUARIO VARCHAR(50) ,
    ID_DOCUMENTO INT ,
    QR_CODE VARCHAR(30) ,
    DATA_ASS DATE ,
    HORA_ASS TIME 
);